"""
Core data models for Sentinel trading platform.

These Pydantic models define the contracts between engines.
Every engine communicates through these types — never raw dicts.
"""

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


# --- Enums ---

class AssetClass(str, Enum):
    EQUITIES = "equities"
    CRYPTO = "crypto"
    PREDICTIONS = "predictions"


class Side(str, Enum):
    BUY = "buy"
    SELL = "sell"


class SignalStrength(str, Enum):
    """How confident the strategy is in this signal."""
    WEAK = "weak"        # < 60% confidence
    MODERATE = "moderate" # 60-80% confidence
    STRONG = "strong"     # > 80% confidence


class RiskDecision(str, Enum):
    APPROVED = "approved"
    REJECTED = "rejected"
    REDUCED = "reduced"  # Approved but at smaller size


class MarketRegime(str, Enum):
    TRENDING_UP = "trending_up"
    TRENDING_DOWN = "trending_down"
    RANGING = "ranging"
    HIGH_VOLATILITY = "high_volatility"
    UNKNOWN = "unknown"


class StrategyStatus(str, Enum):
    ACTIVE = "active"
    PAPER_TESTING = "paper_testing"
    DISABLED = "disabled"
    GRAVEYARD = "graveyard"


# --- Core Models ---

class Signal(BaseModel):
    """A trade signal generated by a Strategy."""
    strategy_id: str
    asset_class: AssetClass
    symbol: str
    side: Side
    quantity: float
    target_price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    confidence: float = Field(ge=0.0, le=1.0)
    strength: SignalStrength
    rationale: str
    market_regime: MarketRegime = MarketRegime.UNKNOWN
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class RiskCheckResult(BaseModel):
    """Result of the Risk Engine evaluating a Signal."""
    decision: RiskDecision
    original_signal: Signal
    approved_quantity: Optional[float] = None  # May be less than requested
    rejection_reasons: list[str] = Field(default_factory=list)
    risk_utilization_pct: float = Field(
        ge=0.0, le=100.0,
        description="How much of total risk budget this trade would use"
    )
    portfolio_value: float
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class TradeResult(BaseModel):
    """Result of executing a trade."""
    trade_id: str
    signal: Signal
    risk_check: RiskCheckResult
    executed: bool
    fill_price: Optional[float] = None
    fill_quantity: Optional[float] = None
    commission: float = 0.0
    slippage: Optional[float] = None  # Difference from target price
    platform: str  # "alpaca", "coinbase", "polymarket", "kalshi"
    error_message: Optional[str] = None
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class PortfolioSnapshot(BaseModel):
    """Point-in-time portfolio state."""
    total_value: float
    cash: float
    positions: dict[str, "PositionInfo"]
    risk_utilization: dict[str, float]  # asset_class -> pct
    daily_pnl: float
    weekly_pnl: float
    total_pnl: float
    drawdown_from_peak: float
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class PositionInfo(BaseModel):
    """Info about a single position."""
    symbol: str
    asset_class: AssetClass
    side: Side
    quantity: float
    entry_price: float
    current_price: float
    unrealized_pnl: float
    pnl_pct: float
    strategy_id: str


class StrategyPerformance(BaseModel):
    """Performance metrics for a single strategy."""
    strategy_id: str
    period_days: int
    trades_count: int
    win_rate: float
    total_pnl: float
    sharpe_ratio: Optional[float] = None
    max_drawdown: float
    profit_factor: Optional[float] = None
    risk_budget_used_pct: float
    status: StrategyStatus


# --- Context Models (for Memory Layer) ---

class StrategyContext(BaseModel):
    """Context assembled for strategy hypothesis generation."""
    market_regime: MarketRegime
    top_strategies: list[StrategyPerformance]
    bottom_strategies: list[StrategyPerformance]
    allocation_by_asset: dict[str, float]
    recent_pnl_7d: float
    recent_pnl_30d: float
    recent_hypotheses: list[str]  # Last 10 hypotheses tested
    portfolio_snapshot: PortfolioSnapshot


class TradeContext(BaseModel):
    """Context assembled for evaluating a trade signal."""
    signal: Signal
    strategy_recent_performance: StrategyPerformance
    portfolio_snapshot: PortfolioSnapshot
    similar_past_trades: list[dict]  # Simplified trade summaries
    market_conditions: dict[str, str]


class RiskContext(BaseModel):
    """Context for risk engine decisions."""
    portfolio_snapshot: PortfolioSnapshot
    correlation_matrix: dict[str, dict[str, float]]
    recent_risk_events: list[dict]
    circuit_breaker_history: list[dict]


# Allow forward references
PortfolioSnapshot.model_rebuild()
